# Site Settings
title: Pogrebni prevozi Edit Aljić
description: Profesionalni međunarodni prevoz pokojnika iz EU u BiH, Srbiju i Crnu Goru. Dostupni 24/7.
url: https://pogrebni-prevozi.github.io
baseurl: ""

# Contact Info
phone: "+386 70 443 005"
phone_display: "+386 70 443 005"
website: https://pogrebni-prevozi.github.io
facebook: https://facebook.com/storitve.aljic
whatsapp: "38670443005"
viber: "38670443005"

# Company Info
company_name: Pogrebni prevozi Edit Aljić S.P.
company_description: Profesionalni međunarodni prevoz pokojnika sa 15+ godina iskustva
established_year: 2008

# SEO
lang: bs
locale: bs_BA
author: Pogrebni prevozi Edit Aljić

# Google Analytics
google_analytics: G-7WMZFXTWKP

# Jekyll Settings
markdown: kramdown
permalink: pretty
timezone: Europe/Sarajevo

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - generate_routes.py

# Include
include:
  - _pages

# Collections
collections:
  relacije:
    output: true
    permalink: /relacije/:path/

# Defaults
defaults:
  # Pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  
  # Relacije
  - scope:
      path: ""
      type: relacije
    values:
      layout: relacija
      author: Edit Aljić

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Tag Settings
social:
  name: Pogrebni prevozi Edit Aljić
  links:
    - https://facebook.com/storitve.aljic
    - https://pogrebne-storitve-aljic.eu
seo:
  keywords:
    - "prevoz pokojnika"
    - "transport umrlih"
    - "pogrebni prevoz"
    - "prevoz pokojnih"
    - "transport pokojnika"
    - "prevoz umrlih osoba"
    - "repatrijacija umrlih"

